---
title: "Cave and karst residing bat infographic "
format: html
author: Sofia Rodas
warning: false
message: false
---

Bats are keystone species for caves and karsts acting as sources of nutrient resources from outside of the bat ecosystem (Tanalgo, 2022). These inputs are vital for the health of cave and karst ecosystems. However, conservation efforts often overlook these less researched and less prominent ecosystems. The database (DarkCideS 1.0)[https://darkcides.wordpress.com/] aims to fill the gap in research by creating an open source database for information on cave and karst dwelling bats. The bats included in DarkCideS 1.0's data includes bats that use caves and karsts at any point in their life cycle. My visual is intended to synthesize some of the information included in the DarkCideS 1.0 database to visualize:  
1. What regions have the most research on cave and karst bats and what regions are most threatened by dense populations and urban areas?  
2. What other ecosystems do cave and karst bats rely on? From which ecosystems are the nutrient sources and other resources entering caves and karsts?   
3. How are the populations of threatened and non-threatened bats changing?   
 
 
 
 ## Design Elements
### Graphic form (you are not limited to just those fundamental chart types discussed in weeks 2 & 4 – explore other chart types and don’t be afraid to get creative with it; check out some of these awesome data viz creators to find inspiration)

### Text (e.g. titles, captions, annotations, axis labels, axis text)

### Themes (i.e. all non-data plot elements; these should be intentionally modified and visually-pleasing)

### Colors

### Typography

### General design (e.g. group order, spacing, text orientation, data-ink ratio, creating a visual hierarchy, avoiding information overload)

### Contextualizing your data

### Entering your primary message

## Considering accessibility (e.g. colorblind-friendly palettes / contrast, alt text)

### Applying a DEI lens to your design, as appropriate (e.g. considering the people / communities / places represented in your data, consider how you frame your questions / issue)


# References
Tanalgo, K.C., Tabora, J.A.G., de Oliveira, H.F.M. et al. DarkCideS 1.0, a global database for bats in karsts and caves. Sci Data 9, 155 (2022). https://doi.org/10.1038/s41597-022-01234-4

Tanalgo, Krizler; Tabora, John Aries G.; Oliveira, Hernani Fernandes Magalhães; Haelewaters, Danny; Beranek, Chad T.; Otálora-Ardila, Aída; et al. (2021). Metadata for: DarkCideS 1.0, a global database for bats in karsts and caves. figshare. Dataset. https://doi.org/10.6084/m9.figshare.16413405.v4