---
title: "exploration"
format: html
message: false
warning: false
---
What does the bat data show?
```{r}
#| message: false
#| warning: false

# load in necessary libraries
library(tidyverse)
```

```{r}
# read in data
bats <- read_csv(here::here("data", "figshare-bat-data", "Dataset_1.csv")) |> 
  janitor::clean_names()
```
```{r}
# view the data 
head(bats)
```

###What are the different feeding groups in this dataset?
```{r}
unique(bats$feeding_groups)
```

```{r}
bat_feeding_groups<- bats |> 
  group_by(feeding_groups) |> 
  summarise(value = n()) |> 
  arrange(value)

ggplot(bat_feeding_groups) +
  geom_col(aes(value, feeding_groups))+
  theme_minimal() +
  theme(axis.title = element_blank()) +
  labs(title = "Number of Bats per Feeding Group")
  
```


###How many species are represented in this dataset?
```{r}
length(unique(bats$species))
```
 So many unique species. 
 
### What region are bats found in most often?
These values are held in columns that are dummy variables. The 

```{r}
ecosystem_bats <- bats |> 
  select(species_name, forest, savanna, dessert, urban, cave) |> 
  mutate(forest = case_when(forest == 1 ~ "forest", 
                            forest == 0 ~ NA)) |> 
  mutate(savanna = case_when(savanna == 1 ~ "savanna", 
                              savanna == 0 ~ NA)) |> 
  mutate(desert = case_when(dessert == 1 ~ "desert",
                            dessert == 0 ~ NA))  |> 
  mutate(urban = case_when(urban == 1 ~ "urban",
                           urban == 0 ~ NA)) |> 
  mutate(cave = case_when(cave == 1 ~ "cave",
                          cave == 0 ~ NA)) |> 
  pivot_longer(cols = c(forest, savanna, desert, urban, cave),
               names_to = "ecosystem_type",
               values_to = "ecosystem") |> 
  filter(!is.na(ecosystem)) |> 
  select(species_name, ecosystem)
```

```{r}
ecosystem_bat_values <- ecosystem_bats |> 
  group_by(ecosystem) |> 
  summarise(value = n()) |> 
  arrange(value)
```

```{r}
ggplot(ecosystem_bat_values, aes(x = "", y = value, fill = ecosystem)) +
  geom_bar(stat = "identity", width = 1, color = "white") +
  coord_polar("y", start = 0) +
  theme_void()
```
What is the breakup of bats feeding groups divided by ecosystem? 
 
```{r}
# join two datasets to get feeding group and ecosystem type
bat_eco_feeding <- full_join(ecosystem_bats, bats, by = "species_name")

# select only the necessary columns
bat_eco_feeding <- bat_eco_feeding |> 
  select(species_name, ecosystem, feeding_groups)

# calculate values for each ecosystem feeding group combination
bat_eco_feeding <- bat_eco_feeding |> 
  group_by(ecosystem, feeding_groups) |> 
  summarise(value = n()) |> 
  arrange(value) |> 
  filter(!is.na(ecosystem)) |> 
  ungroup()
  
```

```{r}
ggplot(bat_eco_feeding) +
  geom_col(aes(value, feeding_groups), fill = "darkblue") +
  facet_wrap(~ecosystem) + 
  theme_minimal()
```
 
